### ISSUE TITLE
witty.er doesn't work on m1 macs

### ISSUE THREAD

**Issue by fleharty** [Illumina/witty.er#19]
Is there a way to use witty.er on M1 macs?

Also, is there a publicly available docker that runs it?

**Comment by Kentalot** [comment]
Yeah, because we're using old libraries and I haven't refreshed the libraries (no plan to for now since we have docker), we don't support it on M1 macs for now.  For the docker, please refer to this: https://github.com/Illumina/witty.er#quick-start  You can build your own image and run.  I don't think there's a public one (at least not from us)

**Comment by Kentalot** [comment]
Actually the next update might have m1 support, i'll try it out.  In the meantime, please try the docker image.

**Comment by Kentalot** [comment]
scratch that, next release will be compatible with M1 macs

**Comment by fleharty** [comment]
@Kentalot Great, thanks!  I was able to build a docker on an x86 machine that I can then run on my M1.  It's much slower, but since it still doesn't take that much time for me it's fine.

**Comment by Kentalot** [comment]
I have pushed a major update to master, please use that branch instead now.  Dockerfile has changed.  There's a bunch of major new features but the README is still in the process of being updated but the normal behavior is still there as well.  You can run --help to see the new options.  It now runs fine on an M1 mac even outside docker.
